name: Security npm dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "25 4 * * MON-FRI" # Every weekday at 04:25 UTC
jobs:
  security-npm-dependency-check:
    permissions:
      contents: read
      actions: read
      security-events: write
    name: Project security npm dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_npm_dependency.yml@v2 # WORKFLOW_VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
